# Generated by Django 5.1.2 on 2024-12-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('assessment', models.DurationField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='semafor.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.worker')),
            ],
            options={
                'unique_together': {('worker', 'project', 'year', 'month')},
            },
        ),
    ]
