# Generated by Django 5.1 on 2024-08-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='projectworkassignment',
            unique_together={('worker', 'project', 'year', 'month')},
        ),
    ]
