# Generated by Django 5.1.4 on 2024-12-17 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0002_workassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('concept', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.ManyToManyField(related_name='transactions', to='semafor.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.project')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='projects',
            field=models.ManyToManyField(related_name='transactions', through='semafor.TransactionProjectAssignment', to='semafor.project'),
        ),
        migrations.CreateModel(
            name='TransactionWorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.transaction')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.worker')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='workers',
            field=models.ManyToManyField(related_name='transactions', through='semafor.TransactionWorkerAssignment', to='semafor.worker'),
        ),
    ]
