# Generated by Django 5.1 on 2024-08-14 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0002_project_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkassignment',
            name='assignment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
