# Generated by Django 5.1.4 on 2025-01-20 18:15

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0003_tag_transaction_transactionprojectassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('repeat', models.CharField(choices=[('NO', 'No'), ('MONTHLY', 'Mensual')], max_length=10)),
            ],
            options={
                'ordering': ['year', 'month', 'concept'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))], verbose_name="Data d'inici"),
        ),
        migrations.CreateModel(
            name='ExpectedTransactionProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.project')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.expectedtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='expectedtransaction',
            name='projects',
            field=models.ManyToManyField(related_name='expected_transactions', through='semafor.ExpectedTransactionProjectAssignment', to='semafor.project'),
        ),
        migrations.CreateModel(
            name='ExpectedTransactionWorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.expectedtransaction')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.worker')),
            ],
        ),
        migrations.AddField(
            model_name='expectedtransaction',
            name='workers',
            field=models.ManyToManyField(related_name='expected_transactions', through='semafor.ExpectedTransactionWorkerAssignment', to='semafor.worker'),
        ),
    ]
