# Generated by Django 5.1 on 2024-09-03 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0003_alter_projectworkassignment_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerMonthDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dedication', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.worker')),
            ],
        ),
    ]
