# Generated by Django 5.1 on 2024-09-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0004_workermonthdedication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workermonthdedication',
            unique_together={('worker', 'year', 'month')},
        ),
    ]
