# Generated by Django 5.1.4 on 2025-03-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0004_expectedtransaction_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=1000, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semafor.project')),
            ],
        ),
    ]
