# Generated by Django 5.2.1 on 2025-05-16 17:17

import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# semafor.migrations.0006_remove_project_date_end_remove_project_date_start_and_more


def delete_alias(apps, schema_editor):
    model = apps.get_model("semafor", "ProjectAlias")
    model.objects.all().delete()


class Migration(migrations.Migration):
    replaces = [
        ("semafor", "0006_remove_project_date_end_remove_project_date_start_and_more"),
        ("semafor", "0007_missingprojectalias"),
        ("semafor", "0008_alter_projectalias_unique_together"),
    ]

    dependencies = [
        ("semafor", "0005_projectalias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="project",
            name="date_start",
        ),
        migrations.RunPython(delete_alias),
        migrations.AddField(
            model_name="projectalias",
            name="worker",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="semafor.worker",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MissingProjectAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=1000, unique=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="semafor.worker"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="projectalias",
            unique_together={("worker", "project")},
        ),
    ]
