# Generated by Django 5.2.1 on 2025-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "semafor",
            "0006_remove_project_date_end_remove_project_date_start_and_more_squashed_0008_alter_projectalias_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="app_id",
            field=models.CharField(
                max_length=1000,
                null=True,
                verbose_name="Identificador de l'usuari a la APP",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="app_token",
            field=models.CharField(
                max_length=100,
                null=True,
                verbose_name="Token d'autorització per a la APP",
            ),
        ),
    ]
