# Generated by Django 5.2.1 on 2025-05-19 15:44
import secrets

from django.db import migrations, models


def set_app_tokens(apps, schema_editor):
    model = apps.get_model("semafor", "Worker")
    for w in model.objects.all():
        w.app_token = secrets.token_urlsafe(50)
        w.save()


class Migration(migrations.Migration):
    dependencies = [
        ("semafor", "0009_worker_app_id_worker_app_token"),
    ]

    operations = [
        migrations.RunPython(set_app_tokens),
        migrations.AlterField(
            model_name="worker",
            name="app_token",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Token d'autorització per a la APP",
            ),
        ),
    ]
