# Generated by Django 5.2.1 on 2025-05-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0010_alter_worker_app_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectalias',
            unique_together={('worker', 'alias')},
        ),
    ]
