# Generated by Django 5.2.1 on 2025-06-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0011_alter_projectalias_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='income',
        ),
    ]
