# Generated by Django 5.2.1 on 2025-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semafor', '0012_remove_project_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectalias',
            name='alias',
            field=models.CharField(max_length=1000),
        ),
    ]
