# Generated by Django 5.2.1 on 2025-09-10 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("semafor", "0013_alter_projectalias_alias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="app_id",
        ),
    ]
